// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLBZYNvextCgBoOud35uKUR1Lff8GyfJ4',
    appId: '1:519686948056:web:8d8f511334159265d543ad',
    messagingSenderId: '519686948056',
    projectId: 'poyen-af6ee',
    authDomain: 'poyen-af6ee.firebaseapp.com',
    databaseURL: 'https://poyen-af6ee-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'poyen-af6ee.appspot.com',
    measurementId: 'G-GB7QTN5WMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLj1KyZ5y_8VD1ufvJK72wnJkTsvmPsM0',
    appId: '1:519686948056:android:02e25d000f2e138fd543ad',
    messagingSenderId: '519686948056',
    projectId: 'poyen-af6ee',
    databaseURL: 'https://poyen-af6ee-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'poyen-af6ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQRONU64tGJCDvHcw1zIFsyrbUx79iYtk',
    appId: '1:519686948056:ios:b139b2745d04ee82d543ad',
    messagingSenderId: '519686948056',
    projectId: 'poyen-af6ee',
    databaseURL: 'https://poyen-af6ee-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'poyen-af6ee.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQRONU64tGJCDvHcw1zIFsyrbUx79iYtk',
    appId: '1:519686948056:ios:b139b2745d04ee82d543ad',
    messagingSenderId: '519686948056',
    projectId: 'poyen-af6ee',
    databaseURL: 'https://poyen-af6ee-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'poyen-af6ee.appspot.com',
    iosBundleId: 'com.example.app',
  );
}
